- hosts: slave1
  become: yes
  roles:
    - java
    - python

- hosts: slave2
  become: yes
  roles:
    - java
    - mysql
    - jenkins

- hosts: slave3
  become: yes
  roles:
    - mysql
    - python